services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: coderspair-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - coderspair-net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: coderspair-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - coderspair-net

networks:
  coderspair-net:
    name: coderspair-net
    driver: bridge
